
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: assessment_development


test:
  <<: *default
  database: assessment_test


#
production:
  <<: *default
  database: assessment_production
  username: assessment
  password: <%= ENV['ASSESSMENT_DATABASE_PASSWORD'] %>
